//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlinkBackend.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlinkMovieEntities : DbContext
    {
        public BlinkMovieEntities()
            : base("name=BlinkMovieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BalanceRequest> BalanceRequests { get; set; }
        public virtual DbSet<Clip> Clips { get; set; }
        public virtual DbSet<Editor> Editors { get; set; }
        public virtual DbSet<Favorite> Favorites { get; set; }
        public virtual DbSet<Genre> Genres { get; set; }
        public virtual DbSet<GetMovie> GetMovies { get; set; }
        public virtual DbSet<History> Histories { get; set; }
        public virtual DbSet<Interest> Interests { get; set; }
        public virtual DbSet<Movie> Movies { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<ReaderRate> ReaderRates { get; set; }
        public virtual DbSet<SentProject> SentProjects { get; set; }
        public virtual DbSet<SentProposal> SentProposals { get; set; }
        public virtual DbSet<Summary> Summaries { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Writer> Writers { get; set; }
    }
}
